export const REQUEST_APP_SCORE = 'REQUEST_APP_SCORE'

export const REQUEST_USER_SCORE = 'REQUEST_USER_SCORE'
export const SUCCESS_USER_SCORE = 'SUCCESS_USER_SCORE'
export const FAILURE_USER_SCORE = 'FAILURE_USER_SCORE'

export const REQUEST_USER_RANK = 'REQUEST_USER_RANK'
export const SUCCESS_USER_RANK = 'SUCCESS_USER_RANK'
export const FAILURE_USER_RANK = 'FAILURE_USER_RANK'

export const REQUEST_USER_UPDATE = 'REQUEST_USER_UPDATE'
export const SUCCESS_USER_UPDATE = 'SUCCESS_USER_UPDATE'
export const FAILURE_USER_UPDATE = 'FAILURE_USER_UPDATE'

export const REQUEST_USER_INFO = 'REQUEST_USER_INFO'
export const SUCCESS_USER_INFO = 'SUCCESS_USER_INFO'
export const FAILURE_USER_INFO = 'FAILURE_USER_INFO'

